# -*- coding: utf-8 -*-
"""Exercício de For.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ukRWitd2ygsBD1xO7MxtxX1YcmdOf-mz
"""

# Faça um programa que leia 5 números e informe o maior número.

maior = 0

for i in range(5):
  n = float(input(f'Digite o {i+1} número: '))
  if n > maior: maior = n
print(f'O maior número digitado foi: {maior}.')

# Faça um programa que verifique e mostre os números entre 1.000 e 2.000 (inclusive) que, quando divididos por 11 produzam resto igual a 2.

for i in range(1000, 2001):
  if i % 11 == 2:
    print(i)

# Faça um programa que leia 5 números e informe a soma e a média dos números.

media = 0

for n in range(5):
  num = float(input(f'Digite o {n+1}º número: '))
  media += num
media /= 5
print(f'A média dos números selecionados é {media}')

# Faça um programa que receba um número e usando laços de repetição calcule e mostre a tabuada desse número.

numero = int(input('Digite um número para ver sua tabuada: '))

for i in range(10):
  conta = numero * (i+1)
  print(f'{numero} x {i+1} = {conta}')

# Faça um programa que mostre as tabuadas dos números de 1 a 10 usando laços de repetição.

for x in range(10):
  for i in range(10):
    print(f'{x+1} x {i+1} = {(x+1)*(i+1)}')
  print()

# Faça um programa que imprima na tela os números de 1 a 20, um abaixo do outro. Depois modifique o programa para que ele mostre os números um ao lado do outro.
for x in range(20):
  print(x+1, end=' ')

# Faça um programa que imprima na tela apenas os números ímpares entre 1 e 50.
for x in range(50):
  if (x+1)%2==1: print(x+1, end=' ')

# Faça um programa que receba dois números inteiros e gere os números inteiros que estão no intervalo compreendido por eles.

n1= int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))

print(f'Os números entre {n1} e {n2}')
for contador in range(n1+1, n2):
  print(contador, end=' ')

# Uma loja deseja cadastrar 5 clientes e verificar se o faturamento da loja foi superior a loja B (faturamento = 54000).
# Se o faturamento atingir esse valor mostre na tela uma mensagem contendo em quanto foi superado o faturamento.

faturamento = 0

for contador in range(5):
  cliente = float(input(f'Qual foi o valor do faturamento do {contador+1}º cliente: R$'))
  faturamento += cliente
if faturamento > 54000:
  print(f'A empresa obteve um lucro de {faturamento-54000:.2f}')
else:
  print(f'A empresa não obteve lucro.')

# Faça um programa que peça 10 números inteiros, calcule e mostre a quantidade de números pares e a quantidade de números impares.
par = 0
impar = 0
for contador in range(10):
  num = int(input(f'Digite o {contador+1}º número: '))
  if num % 2 == 1:
    impar += 1
  else:
    par += 1

print(f'Foi apresentado {impar} números ímpares.\nFoi apresentado {par} números pares.')

# Um funcionário de uma empresa recebe aumento salarial anualmente: Sabe-se que:
# Esse funcionário foi contratado em 1995, com salário inicial de R$ 1.000,00;
# Em 1996 recebeu aumento de 1,5% sobre seu salário inicial;
# A partir de 1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do percentual do ano anterior.
# Faça um programa que determine o salário atual desse funcionário.
# Após concluir isto, altere o programa permitindo que o usuário digite o salário inicial do funcionário.

salario = float(input('Digite o salário: R$'))
porcentagem = 0.015

for contador in range(1996, 2025):
  print(f'{contador} {porcentagem}% {salario*porcentagem}')
  aumento = salario

# Faça um programa que peça uma nota, entre zero e dez.
# Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.

nota = float(input('Digite uma nota: '))

if nota < 0 or nota > 10:
  for x in range(999):
    nota = float(input('ERROR! Digite um valor válido: '))
    if nota >= 0 and nota <= 10: break
print('Nota Validada!')

# Uma loja tem tem uma política de descontos de acordo com o valor da compra do cliente.
# Os descontos começam acima dos R$500. A cada 100 reais acima dos R$500,00 o cliente ganha 1% de desconto cumulativo até 25%.
# Faça um programa que exiba essa tabela de descontos no seguinte formato:
# Valordacompra – porcentagem de desconto – valor final

valor = float(input('Digite o valor da compra: R$'))
contagem = 1

if valor >= 600 and contagem:
  reduzido = valor- 500
  if reduzido >= 100 or contagem <=24:
    for x in range(999):
      contagem += 1
      reduzido -= 100
      if reduzido < 100 or contagem == 24:
        break

porcentagem = contagem / 100
desconto = valor * porcentagem
final = valor - desconto
print(f'O produto de R${valor:.2f} ficará a partir de R${final:.2f} com {contagem:.0f}% de desconto.')

# Faça um programa que receba a idade de 15 pessoas e que calcule e mostre:
# a) A quantidade de pessoas em cada faixa etária;
# b) A percentagem de pessoas na primeira e na última faixa etária, com relação ao total de pessoas:

# Até 15 anos
# De 16 a 30 anos
# De 31 a 45 anos
# De 46 a 60 anos
# Acima de 61 anos

adolescente = jovem = adulto = meiaIdade = idoso = 0


for x in range(5):
  idade = int(input(f'Digite a idade da {x+1}º pessoa: '))
  if idade >= 16 and idade <= 30: jovem += 1              # Até 15 anos
  elif idade >= 31 and idade <= 45: adulto += 1           # De 16 a 30 anos
  elif idade >= 46 and idade <= 60: meiaIdade += 1        # De 31 a 45 anos
  elif idade >= 61: idoso += 1                            # De 46 a 60 anos
  else: adolescente += 1                                  # Acima de 61 anos

print(f'\n\nFaixa etária inserida:\n'
      f'Até 15 anos: {adolescente} pessoas.\n'
      f'De 16 a 30 anos: {jovem} pessoas.\n'
      f'De 31 a 45 anos: {adulto} pessoas.\n'
      f'De 46 a 60 anos: {meiaIdade} pessoas.\n'
      f'Acima de 61 ano: {idoso} pessoas.')

# Faça um programa que peça dois números, base e expoente, calcule e mostre o primeiro número elevado ao segundo número.
# Não utilize a função de potência da linguagem.

base = int(input('Digite o primeiro valor: '))
expoente = int(input('Digite o segundo valor: '))
resultado = 1

for x in range(expoente):
  resultado *= base

print(f'A base {base} em exponenciação com {expoente} resulta em: {resultado}.')

# Faça um programa que mostre todos os primos entre 1 e N sendo N um número inteiro fornecido pelo usuário.
# O programa deverá mostrar também o número de divisões que ele executou para encontrar os números primos.
# Serão avaliados o funcionamento, o estilo e o número de testes (divisões) executados.

n = int(input("Digite um número: "))

for numeroTestado in range(1, n+1):
 for numeroDivisor in range(numeroTestado):
  print(f"{numeroTestado} / {numeroDivisor+1} = {numeroTestado /(numeroDivisor+1)} com o resto {numeroTestado%(numeroDivisor+1)}")
  if numeroTestado % (numeroDivisor+1) == 0:
    if 1 != numeroDivisor+1 != numeroTestado:
      print("não é primo\n")
      break
    elif numeroDivisor+1 == numeroTestado:
       print("número é primo\n")